### ISSUE TITLE
`overlapping_axes` should be renamed to `intersect_axes`

### ISSUE THREAD

**Issue by cooljoseph1** [stanford-crfm/haliax#108]
Right now `haliax.overlapping_axes` returns the intersection of two axes specifications, and raises an error if two axes of the same name have different sizes. I contend that this function should be renamed `haliax.intersect_axes` for two reasons:

1. It is the direct counterpart of `haliax.union_axes`
2. It returns axes, not the axes' names. In particular, it raises an error if two axes are named the same but have different sizes. The word *overlapping* suggests that it could be used to get the names in common between two axes specs--such as if you want to check if you need to rename any of them. Throwing an error is strange behavior here.

Hence, I suggest that `haliax.overlapping_axes` be renamed to `haliax.intersect_axes`, and the function  `haliax.overlapping_axes` be changed to return the intersection of the axes' *names*.

The main reason to not make this change is that it would break the API, and that might be reason enough to leave it as is.

**Comment by dlwh** [comment]
sounsd good to me. i'd merge this

**Comment by cooljoseph1** [comment]
Okay, I opened a pull request.
