### ISSUE TITLE
jax.random.KeyArray deprecated

### ISSUE THREAD

**Issue by jennifgcrl** [stanford-crfm/haliax#75]
As per jax [changelog](https://jax.readthedocs.io/en/latest/changelog.html), from jax 0.4.24 on `jax.random.KeyArray` is no longer, so haliax fails to import with
```
AttributeError: module 'jax.random' has no attribute 'KeyArray'
```

**Comment by dlwh** [comment]
oops, ok, will fix soon!

**Comment by dlwh** [comment]
i fixed this at some point
